name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macOS-latest, windows-2019]
        version: ['stable', 'insiders']

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Dependencies
        run: 'npm ci || npm ci'
        shell: bash
      
      - name: Lint check
        if: startsWith(matrix.os, 'ubuntu') && matrix.version == 'stable'
        run: npm run lint

      - name: Style check
        if: startsWith(matrix.os, 'ubuntu') && matrix.version == 'stable'
        run: npm run style-check

      - name: Compile sources
        run: npm run build
      
      - name: Cache VSCode binary
        id: cache-vscode
        uses: actions/cache@v1
        with:
          path: .vscode-test
          key: vscode-${{ runner.os }}-${{matrix.version}}
          restore-keys: |
            vscode-${{ runner.os }}-${{matrix.version}}
            vscode-${{ runner.os }}-

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test
        env:
          CODE_VERSION: ${{ matrix.version }}

      - name: Prepare artifact
        if: startsWith(matrix.os, 'ubuntu') && matrix.version == 'stable' && github.event_name == 'pull_request'
        uses: lannonbr/vsce-action@master
        with:
          args: "package -o svn-scm.vsix"

      - name: Upload artifact
        if: startsWith(matrix.os, 'ubuntu') && matrix.version == 'stable' && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v1
        with:
          name: svn-scm.vsix
          path: svn-scm.vsix

      - name: Release
        if: startsWith(matrix.os, 'ubuntu') && matrix.version == 'stable' && github.ref == 'refs/heads/master' && github.repository == 'JohnstonCode/svn-scm'
        run: npm run semantic-release
        env:
          VSCE_TOKEN: ${{ secrets.vsceToken }}
          GITHUB_TOKEN: ${{ secrets.githubToken }}
          GH_TOKEN: ${{ secrets.githubToken }}
          GIT_AUTHOR_EMAIL: ${{ secrets.gitEmail }}
          GIT_COMMITTER_EMAIL: ${{ secrets.gitEmail }}
          GIT_AUTHOR_NAME: ${{ secrets.gitName }}
          GIT_COMMITTER_NAME: ${{ secrets.gitName }}
